In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
le = LabelEncoder()
df = pd.read_csv('compas-scores-two-years.csv')

columns = ['sex','race','age_cat', 
           'priors_count','juv_fel_count','r_charge_degree','two_year_recid']


df['sex'] = le.fit_transform(df['sex'])
df['age_cat'] = le.fit_transform(df['age_cat'])
#df['race'] = le.fit_transform(df['race'])
df['race'] = df['race'].transform(lambda x: 1 if x=='Caucasian' else 0)
df['r_charge_degree'] = df['r_charge_degree'].transform(lambda x: '0' if str(x)=='nan' else x)
df['r_charge_degree'] = le.fit_transform(df['r_charge_degree'])
df = df[columns]
# df['juv_fel_count'] = df['juv_other_count'] + df['juv_misd_count'] + df['juv_fel_count'] 
# df = df.drop(columns=['juv_other_count','juv_misd_count'])
model = LogisticRegression()
X = df.to_numpy()[:,:-1]
y = df.to_numpy()[:,-1]
X_train, X_text, y_train, y_test = train_test_split(X, y,train_size=0.8)
model.fit(X_train, y_train)
print('Acc',model.score(X_text, y_test))
pred = model.predict(X_text)
print('F1',f1_score(y_test,pred))

Acc 0.9667359667359667
F1 0.9636913767019667

In [176]:
df1=pd.read_csv('compas')
df1=df1[['sex','race','age', 
           'priors_count','juv_fel_count','c_charge_degree','label']]
model = LogisticRegression()
X = df1.to_numpy()[:,:-1]
y = df1.to_numpy()[:,-1]
X_train, X_text, y_train, y_test = train_test_split(X, y,train_size=0.8)
model.fit(X_train, y_train)
print('Acc',model.score(X_text, y_test))
pred = model.predict(X_text)
print('F1',f1_score(y_test,pred))

Acc 0.6431046431046431
F1 0.5661331086773378

In [183]:
df.columns

Index(['id', 'name', 'first', 'last', 'compas_screening_date', 'sex', 'dob',
       'age', 'age_cat', 'race', 'juv_fel_count', 'decile_score',
       'juv_misd_count', 'juv_other_count', 'priors_count',
       'days_b_screening_arrest', 'c_jail_in', 'c_jail_out', 'c_case_number',
       'c_offense_date', 'c_arrest_date', 'c_days_from_compas',
       'c_charge_degree', 'c_charge_desc', 'is_recid', 'r_case_number',
       'r_charge_degree', 'r_days_from_arrest', 'r_offense_date',
       'r_charge_desc', 'r_jail_in', 'r_jail_out', 'violent_recid',
       'is_violent_recid', 'vr_case_number', 'vr_charge_degree',
       'vr_offense_date', 'vr_charge_desc', 'type_of_assessment',
       'decile_score.1', 'score_text', 'screening_date',
       'v_type_of_assessment', 'v_decile_score', 'v_score_text',
       'v_screening_date', 'in_custody', 'out_custody', 'priors_count.1',
       'start', 'end', 'event', 'two_year_recid'],
      dtype='object')

In [6]:
pd.read_csv('compas-scores-two-years.csv').iloc[6]

id                                                      8
name                                        edward riddle
first                                              edward
last                                               riddle
compas_screening_date                          2014-02-19
sex                                                  Male
dob                                            1974-07-23
age                                                    41
age_cat                                           25 - 45
race                                            Caucasian
juv_fel_count                                           0
decile_score                                            6
juv_misd_count                                          0
juv_other_count                                         0
priors_count                                           14
days_b_screening_arrest                              -1.0
c_jail_in                             2014-02-18 05:08:24
c_jail_out                            2014-02-24 12:18:30
c_case_number                               14002304CF10A
c_offense_date                                 2014-02-18
c_arrest_date                                         NaN
c_days_from_compas                                    1.0
c_charge_degree                                         F
c_charge_desc                   Possession Burglary Tools
is_recid                                                1
r_case_number                               14004485CF10A
r_charge_degree                                      (F2)
r_days_from_arrest                                    0.0
r_offense_date                                 2014-03-31
r_charge_desc              Poss of Firearm by Convic Felo
r_jail_in                                      2014-03-31
r_jail_out                                     2014-04-18
violent_recid                                         NaN
is_violent_recid                                        0
vr_case_number                                        NaN
vr_charge_degree                                      NaN
vr_offense_date                                       NaN
vr_charge_desc                                        NaN
type_of_assessment                     Risk of Recidivism
decile_score.1                                          6
score_text                                         Medium
screening_date                                 2014-02-19
v_type_of_assessment                     Risk of Violence
v_decile_score                                          2
v_score_text                                          Low
v_screening_date                               2014-02-19
in_custody                                     2014-03-31
out_custody                                    2014-04-18
priors_count.1                                         14
start                                                   5
end                                                    40
event                                                   1
two_year_recid                                          1
Name: 6, dtype: object

In [5]:
df.loc[df['race']==1]

,sex,race,age_cat,priors_count,juv_fel_count,r_charge_degree,two_year_recid
6,1,1,0,14,0,2,1
8,0,1,0,0,0,10,0
9,1,1,2,1,0,7,1
10,1,1,0,0,0,10,0
12,0,1,0,0,0,10,0
...,...,...,...,...,...,...,...
7192,1,1,0,0,0,10,0
7194,0,1,0,2,0,3,1
7199,1,1,2,0,0,10,0
7205,1,1,2,5,0,8,1
7206,1,1,2,0,0,7,1

In [221]:
df.min(),df.max()

(sex                0
 race               0
 age_cat            0
 priors_count       0
 juv_fel_count      0
 r_charge_degree    0
 two_year_recid     0
 dtype: int64,
 sex                 1
 race                1
 age_cat             2
 priors_count       38
 juv_fel_count      20
 r_charge_degree    10
 two_year_recid      1
 dtype: int64)